server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ums_db
    username: root
    password: AbdulBasit94
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect